version: "3.9"

services:

  prometheus:
    container_name: radar-prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/ready"]
      interval: 5s
      timeout: 3s
      retries: 10

  alertmanager:
    container_name: radar-alertmanager
    image: prom/alertmanager
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=info
    ports:
      - "9093:9093"
    depends_on:
      - prometheus

  ingestor:
    container_name: radar-ingestor
    build: ./ingestor-service
    ports:
      - "8081:8080"    # <-- ESTE ES EL PUERTO AL QUE ENVÃAS CURLs
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      prometheus:
        condition: service_healthy

  analyzer:
    container_name: radar-analyzer
    build: ./analyzer-service
    ports:
      - "8082:8080"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090   # Lectura directa
    depends_on:
      prometheus:
        condition: service_healthy
      alertmanager:
        condition: service_started

  dashboard:
    container_name: radar-dashboard
    image: nginx:latest
    volumes:
      - ./dashboard:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - analyzer
